/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bil481hw1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;
import java.util.Arrays;


class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    
    @Test
    public void testDividible() {
       ArrayList<Integer> array = new ArrayList<>(Arrays.asList(5,10,9,20,24));
       assertTrue(App.dividible(array, 3,2));
     }
 
     @Test
     public void testNotDividible() {
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(2,4,6,8,10,14));
        assertFalse(App.dividible(array, 5,3));
      }
 
     @Test
     public void testEmptyArray() {
       ArrayList<Integer> array = new ArrayList<>();
       assertFalse(App.dividible(array, 10,1));
     }
 
     @Test
     public void testNull() {
       assertFalse(App.dividible(null, 4,2));
     }
 }
