/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bil481hw1;
import java.util.ArrayList;
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

      //returns true if any integer in the array is dividibleByMult (x%y=0) to the multiply of given integers.
      public static boolean dividibleByMult(ArrayList<Integer> array, int e, int f){
          System.out.println("Checking divisibility");
          if(e  < 0 && f < 0) return true;
          if(e  < 0 || f < 0) return false;
          if (array == null) return false;
          else if( array.size() == 0) return false;
          for (int elt : array) {
            if (elt % (e*f) == 0) return true;
        }
          return false;
      }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
